---
abstract: 'A reasonable Maildir/Maildir++ delivery mechanism'
author:
  - 'Xan Tronix <xan@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.140640'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mail-Dir
no_index:
  directory:
    - t
    - inc
requires:
  Sys::Hostname: '0'
resources:
  Type: git
  Url: git://github.com/xantronix/Mail-Dir.git
  Web: https://github.com/xantronix/Mail-Dir
version: '0.01'
